/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HouseholdsJoinRouteImport } from './routes/households/join'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'

const HouseholdsJoinRoute = HouseholdsJoinRouteImport.update({
  id: '/households/join',
  path: '/households/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/households/join': typeof HouseholdsJoinRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
}
export interface FileRoutesByTo {
  '/households/join': typeof HouseholdsJoinRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/households/join': typeof HouseholdsJoinRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/households/join' | '/invitations/accept'
  fileRoutesByTo: FileRoutesByTo
  to: '/households/join' | '/invitations/accept'
  id: '__root__' | '/households/join' | '/invitations/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HouseholdsJoinRoute: typeof HouseholdsJoinRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/households/join': {
      id: '/households/join'
      path: '/households/join'
      fullPath: '/households/join'
      preLoaderRoute: typeof HouseholdsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HouseholdsJoinRoute: HouseholdsJoinRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
