#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
TARGET_ENV="${ROOT_DIR}/.env.local"
WORKTREE_ENV="${ROOT_DIR}/.env.worktree"
MODE="${WORKTREE_ENV_MODE:-symlink}"
SOURCE_ENV="${WORKTREE_ENV_FILE:-${CODEX_WORKTREE_ENV_FILE:-}}"
GIT_COMMON_DIR="$(cd "${ROOT_DIR}" && cd "$(git rev-parse --git-common-dir)" && pwd -P)"
RESERVATION_LOCK_DIR="${GIT_COMMON_DIR}/dont-forget-worktree-env.lock"
LOCK_HELD=0

API_PORT_BASE=18080
WEB_PORT_BASE=13000
PORT_SLOT_COUNT=1000
LOCK_TIMEOUT_SECONDS=10

LIVE_WORKTREES=()
RESERVED_API_PORTS=()
RESERVED_WEB_PORTS=()
RESERVED_ENV_PATHS=()
CURRENT_WORKTREE="$(cd "${ROOT_DIR}" && pwd -P)"

fail() {
	echo "$1" >&2
	exit "${2:-1}"
}

release_reservation_lock() {
	if [[ "${LOCK_HELD}" == "1" ]]; then
		rmdir "${RESERVATION_LOCK_DIR}" 2>/dev/null || true
		LOCK_HELD=0
	fi
}

trap release_reservation_lock EXIT
trap 'release_reservation_lock; trap - HUP; kill -HUP "$$"' HUP
trap 'release_reservation_lock; trap - INT; kill -INT "$$"' INT
trap 'release_reservation_lock; trap - TERM; kill -TERM "$$"' TERM

acquire_reservation_lock() {
	local elapsed_seconds=0

	while ! mkdir "${RESERVATION_LOCK_DIR}" 2>/dev/null; do
		if ((elapsed_seconds >= LOCK_TIMEOUT_SECONDS)); then
			fail "Timed out acquiring worktree env lock: ${RESERVATION_LOCK_DIR}"
		fi
		sleep 1
		elapsed_seconds=$((elapsed_seconds + 1))
	done

	LOCK_HELD=1
}

is_decimal() {
	[[ "$1" =~ ^[1-9][0-9]*$ ]]
}

canonical_existing_dir() {
	(cd "$1" && pwd -P)
}

record_live_worktree() {
	local worktree_path="$1"
	local is_prunable="$2"

	if [[ -z "${worktree_path}" || "${is_prunable}" == "1" || ! -d "${worktree_path}" ]]; then
		return
	fi

	LIVE_WORKTREES+=("$(canonical_existing_dir "${worktree_path}")")
}

load_live_worktrees() {
	local field=""
	local worktree_path=""
	local is_prunable="0"

	LIVE_WORKTREES=()
	while IFS= read -r -d '' field; do
		if [[ -z "${field}" ]]; then
			record_live_worktree "${worktree_path}" "${is_prunable}"
			worktree_path=""
			is_prunable="0"
			continue
		fi

		case "${field}" in
			worktree\ *)
				if [[ -n "${worktree_path}" ]]; then
					record_live_worktree "${worktree_path}" "${is_prunable}"
				fi
				worktree_path="${field#worktree }"
				is_prunable="0"
				;;
			prunable*)
				is_prunable="1"
				;;
		esac
	done < <(git -C "${ROOT_DIR}" worktree list --porcelain -z)

	record_live_worktree "${worktree_path}" "${is_prunable}"
}

file_mode() {
	local env_path="$1"
	local mode=""

	if mode="$(stat -f "%Lp" "${env_path}" 2>/dev/null)" && [[ "${mode}" =~ ^[0-7]{3,4}$ ]]; then
		echo "${mode}"
		return
	fi
	if mode="$(stat -c "%a" "${env_path}" 2>/dev/null)" && [[ "${mode}" =~ ^[0-7]{3,4}$ ]]; then
		echo "${mode}"
		return
	fi

	fail "Could not read .env.worktree permissions: ${env_path}"
}

validate_worktree_env() {
	local env_path="$1"
	local mode=""
	local api_port=""
	local web_port=""
	local public_web_base_url=""
	local line=""
	local key=""
	local value=""
	local separator=""

	if [[ -L "${env_path}" ]]; then
		fail ".env.worktree must be a regular file, not a symlink: ${env_path}"
	fi
	if [[ ! -f "${env_path}" ]]; then
		fail ".env.worktree must be a regular file: ${env_path}"
	fi
	mode="$(file_mode "${env_path}")"
	if [[ "${mode}" != "600" ]]; then
		fail ".env.worktree must have permissions 0600: ${env_path}"
	fi

	while IFS= read -r line || [[ -n "${line}" ]]; do
		case "${line}" in
			"" | "# Generated by make worktree-env. Do not edit." | "# Contains only checkout-local API_PORT, WEB_PORT, and PUBLIC_WEB_BASE_URL values." | "# localhost is for Simulator/browser use; physical-iPhone links need a reachable HTTPS origin.")
				continue
				;;
			*=*)
				separator="${line%%=*}"
				key="${separator}"
				value="${line#*=}"
				;;
			*)
				fail "Malformed .env.worktree line in ${env_path}"
				;;
		esac

		case "${key}" in
			API_PORT)
				if [[ -n "${api_port}" ]]; then
					fail "Duplicate API_PORT in ${env_path}"
				fi
				api_port="${value}"
				;;
			WEB_PORT)
				if [[ -n "${web_port}" ]]; then
					fail "Duplicate WEB_PORT in ${env_path}"
				fi
				web_port="${value}"
				;;
			PUBLIC_WEB_BASE_URL)
				if [[ -n "${public_web_base_url}" ]]; then
					fail "Duplicate PUBLIC_WEB_BASE_URL in ${env_path}"
				fi
				public_web_base_url="${value}"
				;;
			*)
				fail "Unexpected key ${key} in ${env_path}"
				;;
		esac
	done < "${env_path}"

	if [[ -z "${api_port}" || -z "${web_port}" || -z "${public_web_base_url}" ]]; then
		fail "Missing required generated keys in ${env_path}"
	fi
	if ! is_decimal "${api_port}" || ! is_decimal "${web_port}"; then
		fail "API_PORT and WEB_PORT must be decimal integers in ${env_path}"
	fi
	if ((api_port < API_PORT_BASE || api_port >= API_PORT_BASE + PORT_SLOT_COUNT)); then
		fail "API_PORT is outside the worktree allocation range in ${env_path}"
	fi
	if ((web_port < WEB_PORT_BASE || web_port >= WEB_PORT_BASE + PORT_SLOT_COUNT)); then
		fail "WEB_PORT is outside the worktree allocation range in ${env_path}"
	fi
	if ((api_port - API_PORT_BASE != web_port - WEB_PORT_BASE)); then
		fail "API_PORT and WEB_PORT slots do not match in ${env_path}"
	fi
	if [[ "${public_web_base_url}" != "http://localhost:${web_port}" ]]; then
		fail "PUBLIC_WEB_BASE_URL must match WEB_PORT in ${env_path}"
	fi

	VALID_API_PORT="${api_port}"
	VALID_WEB_PORT="${web_port}"
}

find_port_owner() {
	local api_port="$1"
	local web_port="$2"
	local index=0

	for index in "${!RESERVED_ENV_PATHS[@]}"; do
		if [[
			"${RESERVED_API_PORTS[${index}]}" == "${api_port}" ||
			"${RESERVED_WEB_PORTS[${index}]}" == "${web_port}"
		]]; then
			echo "${RESERVED_ENV_PATHS[${index}]}"
			return 0
		fi
	done

	return 1
}

reserve_worktree_envs() {
	local live_worktree=""
	local env_path=""
	local owner=""

	RESERVED_API_PORTS=()
	RESERVED_WEB_PORTS=()
	RESERVED_ENV_PATHS=()
	for live_worktree in "${LIVE_WORKTREES[@]}"; do
		env_path="${live_worktree}/.env.worktree"
		if [[ ! -e "${env_path}" && ! -L "${env_path}" ]]; then
			continue
		fi

		validate_worktree_env "${env_path}"
		owner="$(find_port_owner "${VALID_API_PORT}" "${VALID_WEB_PORT}" || true)"
		if [[ -n "${owner}" ]]; then
			fail "Port collision between ${env_path} and ${owner}"
		fi
		RESERVED_API_PORTS+=("${VALID_API_PORT}")
		RESERVED_WEB_PORTS+=("${VALID_WEB_PORT}")
		RESERVED_ENV_PATHS+=("${env_path}")
	done
}

ensure_current_worktree_env() {
	local owner=""
	local current_api_port=""
	local current_web_port=""
	local checksum=""
	local initial_slot=""
	local offset=0
	local slot=0
	local api_port=0
	local web_port=0
	local temp_file=""

	if [[ -e "${WORKTREE_ENV}" || -L "${WORKTREE_ENV}" ]]; then
		validate_worktree_env "${WORKTREE_ENV}"
		current_api_port="${VALID_API_PORT}"
		current_web_port="${VALID_WEB_PORT}"
		owner="$(find_port_owner "${current_api_port}" "${current_web_port}" || true)"
		if [[ -n "${owner}" && "${owner}" != "${WORKTREE_ENV}" ]]; then
			fail "Port collision between ${WORKTREE_ENV} and ${owner}"
		fi
		echo ".env.worktree already exists in ${ROOT_DIR}"
		return
	fi

	checksum="$(printf '%s' "${CURRENT_WORKTREE}" | cksum | awk '{print $1}')"
	initial_slot=$((checksum % PORT_SLOT_COUNT))

	for ((offset = 0; offset < PORT_SLOT_COUNT; offset += 1)); do
		slot=$(((initial_slot + offset) % PORT_SLOT_COUNT))
		api_port=$((API_PORT_BASE + slot))
		web_port=$((WEB_PORT_BASE + slot))
		if ! find_port_owner "${api_port}" "${web_port}" >/dev/null; then
			temp_file="$(mktemp "${ROOT_DIR}/.env.worktree.tmp.XXXXXX")"
			chmod 0600 "${temp_file}"
			{
				echo "# Generated by make worktree-env. Do not edit."
				echo "# Contains only checkout-local API_PORT, WEB_PORT, and PUBLIC_WEB_BASE_URL values."
				echo "# localhost is for Simulator/browser use; physical-iPhone links need a reachable HTTPS origin."
				echo "API_PORT=${api_port}"
				echo "WEB_PORT=${web_port}"
				echo "PUBLIC_WEB_BASE_URL=http://localhost:${web_port}"
			} > "${temp_file}"

			if ! ln "${temp_file}" "${WORKTREE_ENV}"; then
				rm -f "${temp_file}"
				fail "Refusing to replace existing .env.worktree: ${WORKTREE_ENV}"
			fi

			rm -f "${temp_file}"
			echo "Created .env.worktree with API_PORT=${api_port} WEB_PORT=${web_port}"
			return
		fi
	done

	fail "No available checkout-local API_PORT/WEB_PORT pair in ${PORT_SLOT_COUNT} slots"
}

load_live_worktrees

if [[ -z "${SOURCE_ENV}" ]]; then
	for CANDIDATE_WORKTREE_PATH in "${LIVE_WORKTREES[@]}"; do
		if [[
			"${CANDIDATE_WORKTREE_PATH}" != "${CURRENT_WORKTREE}" &&
			-f "${CANDIDATE_WORKTREE_PATH}/.env.local"
		]]; then
			SOURCE_ENV="${CANDIDATE_WORKTREE_PATH}/.env.local"
			break
		fi
	done
fi

if [[ ! -e "${TARGET_ENV}" && ! -L "${TARGET_ENV}" && ( -z "${SOURCE_ENV}" || ! -f "${SOURCE_ENV}" ) ]]; then
	cat >&2 <<'MESSAGE'
No source .env.local was found.

Create one from .env.example or point to an existing local env file:

  WORKTREE_ENV_FILE=/path/to/.env.local make worktree-env

By default this command symlinks the env file. To copy instead:

  WORKTREE_ENV_MODE=copy WORKTREE_ENV_FILE=/path/to/.env.local make worktree-env
MESSAGE
	exit 1
fi

if [[ -e "${TARGET_ENV}" || -L "${TARGET_ENV}" ]]; then
	echo ".env.local already exists in ${ROOT_DIR}"
else
	case "${MODE}" in
		symlink)
			ln -s "${SOURCE_ENV}" "${TARGET_ENV}"
			echo "Linked .env.local -> ${SOURCE_ENV}"
			;;
		copy)
			cp "${SOURCE_ENV}" "${TARGET_ENV}"
			chmod 0600 "${TARGET_ENV}"
			echo "Copied .env.local from ${SOURCE_ENV}"
			;;
		*)
			echo "Unsupported WORKTREE_ENV_MODE=${MODE}. Use symlink or copy." >&2
			exit 2
			;;
	esac
fi

acquire_reservation_lock
load_live_worktrees
reserve_worktree_envs
ensure_current_worktree_env
