name: Production App Store Connect Upload

on:
  workflow_dispatch: {}

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  require_approval:
    name: Approve production release
    type: require-approval

  deploy_api:
    name: Deploy production API
    needs: [require_approval]
    type: deploy
    environment: production
    env:
      APP_ENV: production
    params:
      prod: true

  build_ios:
    name: Build production iOS
    needs: [deploy_api]
    type: build
    environment: production
    env:
      APP_ENV: production
    params:
      platform: ios
      profile: production
      message: Production App Store Connect upload

  submit_ios:
    name: Submit production iOS
    needs: [build_ios]
    type: submit
    environment: production
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
