import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
	backdrop: {
		flex: 1,
		justifyContent: "flex-end",
		backgroundColor: "rgba(15, 23, 42, 0.32)",
	},
	sheet: {
		maxHeight: "72%",
		paddingHorizontal: theme.spacing(5),
		paddingTop: theme.spacing(5),
		paddingBottom: theme.spacing(8),
		backgroundColor: theme.colors.surface,
		borderTopLeftRadius: theme.radii.card,
		borderTopRightRadius: theme.radii.card,
		gap: theme.spacing(4),
	},
	createForm: {
		gap: theme.spacing(4),
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: theme.spacing(3),
	},
	segmentedControl: {
		flexDirection: "row",
		padding: theme.spacing(1),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		backgroundColor: theme.colors.background,
		gap: theme.spacing(1),
	},
	segmentButton: {
		minHeight: theme.spacing(10),
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
	},
	segmentButtonActive: {
		backgroundColor: theme.colors.surface,
		borderWidth: theme.borders.thin,
		borderColor: theme.colors.border,
	},
	segmentButtonLabel: {
		...theme.typography.callout,
		color: theme.colors.textMuted,
		fontWeight: theme.fontWeights.bold,
	},
	segmentButtonLabelActive: {
		color: theme.colors.text,
	},
	searchGroup: {
		flexDirection: "row",
		alignItems: "center",
		gap: theme.spacing(2),
	},
	clearSearchButton: {
		minHeight: theme.spacing(10),
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: theme.spacing(3),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		backgroundColor: theme.colors.background,
	},
	clearSearchLabel: {
		...theme.typography.captionStrong,
		color: theme.colors.primary,
	},
	title: {
		...theme.typography.headline,
		color: theme.colors.text,
	},
	formHelp: {
		...theme.typography.callout,
		color: theme.colors.textMuted,
	},
	closeButton: {
		minHeight: theme.spacing(10),
		paddingHorizontal: theme.spacing(3),
		alignItems: "center",
		justifyContent: "center",
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		backgroundColor: theme.colors.background,
	},
	closeButtonLabel: {
		...theme.typography.callout,
		color: theme.colors.text,
		fontWeight: theme.fontWeights.bold,
	},
	rows: {
		flexGrow: 0,
	},
	rowsContent: {
		gap: theme.spacing(2),
	},
	rowGroup: {
		gap: theme.spacing(1),
	},
	row: {
		minHeight: theme.spacing(14),
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		borderWidth: theme.borders.thin,
		borderColor: theme.colors.border,
		backgroundColor: theme.colors.background,
		overflow: "hidden",
	},
	rowMain: {
		minHeight: theme.spacing(14),
		flex: 1,
		minWidth: 0,
		gap: theme.spacing(1),
		paddingHorizontal: theme.spacing(4),
		paddingVertical: theme.spacing(3),
	},
	rowAction: {
		minHeight: theme.spacing(14),
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: theme.spacing(3),
		borderLeftWidth: theme.borders.hairline,
		borderLeftColor: theme.colors.border,
	},
	rowActionLabel: {
		...theme.typography.captionStrong,
		color: theme.colors.primary,
	},
	rowActionMenu: {
		alignItems: "flex-end",
		gap: theme.spacing(1),
	},
	menuAction: {
		minHeight: theme.spacing(10),
		minWidth: theme.spacing(24),
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: theme.spacing(4),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		borderWidth: theme.borders.thin,
		borderColor: theme.colors.border,
		backgroundColor: theme.colors.background,
	},
	menuActionLabel: {
		...theme.typography.callout,
		color: theme.colors.text,
		fontWeight: theme.fontWeights.bold,
	},
	destructiveMenuActionLabel: {
		...theme.typography.callout,
		color: theme.colors.destructive,
		fontWeight: theme.fontWeights.bold,
	},
	currentRow: {
		borderColor: theme.colors.primary,
		backgroundColor: "#E6F4EA",
	},
	disabledRow: {
		opacity: theme.opacities.disabled,
	},
	rowName: {
		minWidth: 0,
		...theme.typography.body,
		color: theme.colors.text,
		fontWeight: theme.fontWeights.semibold,
	},
	rowMeta: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: theme.spacing(2),
	},
	rowMetaText: {
		...theme.typography.caption,
		color: theme.colors.textMuted,
	},
	currentLabel: {
		...theme.typography.captionStrong,
		color: theme.colors.primary,
	},
	emptyState: {
		alignItems: "center",
		gap: theme.spacing(3),
		paddingVertical: theme.spacing(6),
	},
	emptyStateTitle: {
		...theme.typography.callout,
		color: theme.colors.textMuted,
		fontWeight: theme.fontWeights.bold,
		textAlign: "center",
	},
	emptyStateActions: {
		alignSelf: "stretch",
		gap: theme.spacing(2),
	},
	footerActions: {
		paddingTop: theme.spacing(1),
	},
	fieldGroup: {
		gap: theme.spacing(2),
	},
	inputLabel: {
		...theme.typography.captionStrong,
		color: theme.colors.textMuted,
	},
	input: {
		minHeight: theme.spacing(12),
		flex: 1,
		paddingHorizontal: theme.spacing(3.5),
		paddingVertical: theme.spacing(2.5),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		borderWidth: theme.borders.thin,
		borderColor: theme.colors.border,
		backgroundColor: theme.colors.background,
		...theme.typography.body,
		color: theme.colors.text,
	},
	validationText: {
		...theme.typography.caption,
		color: theme.colors.destructive,
	},
	errorText: {
		...theme.typography.caption,
		color: theme.colors.destructive,
	},
	formActions: {
		flexDirection: "row",
		gap: theme.spacing(3),
	},
	primaryButton: {
		minHeight: theme.spacing(12),
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: theme.spacing(4),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		backgroundColor: theme.colors.primary,
	},
	primaryButtonLabel: {
		...theme.typography.callout,
		color: theme.colors.inverseText,
		fontWeight: theme.fontWeights.bold,
	},
	destructiveButton: {
		minHeight: theme.spacing(12),
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: theme.spacing(4),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		backgroundColor: theme.colors.destructive,
	},
	destructiveButtonLabel: {
		...theme.typography.callout,
		color: theme.colors.inverseText,
		fontWeight: theme.fontWeights.bold,
	},
	secondaryButton: {
		minHeight: theme.spacing(12),
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: theme.spacing(4),
		borderRadius: theme.radii.control,
		borderCurve: "continuous",
		borderWidth: theme.borders.thin,
		borderColor: theme.colors.border,
		backgroundColor: theme.colors.background,
	},
	secondaryButtonLabel: {
		...theme.typography.callout,
		color: theme.colors.text,
		fontWeight: theme.fontWeights.bold,
	},
	pressed: {
		opacity: theme.opacities.pressed,
	},
}));
